### ISSUE TITLE
启动报错啊，表不完整

### ISSUE THREAD

**Issue by fqqgb365** [zhaopei8948/maintain#1]
你好, 表都不完整,可以写个文档吗

**Comment by zhaopei0418** [comment]
你好，这里边几个数据库都是内部的没办法提供，很抱歉。


赵配

18537215680

________________________________
发件人: fqqgb365 <notifications@github.com>
发送时间: 2017年3月23日 18:48:06
收件人: zhaopei0418/maintain
抄送: Subscribed
主题: [zhaopei0418/maintain] 启动报错啊，表不完整 (#1)


你好, 表都不完整,可以写个文档吗

―
